### ISSUE TITLE
Support Docker for Mac

### ISSUE THREAD

**Issue by griff** [rust-embedded/cross#102]
Right now on macOS host when target is not for macOS cross simply does nothing and calls cargo directly. But with Docker for Mac running it should be possible to cross compile to all targets that cross supports using docker.

**Comment by japaric** [comment]
Sounds good to me! Travis CI doesn't support docker for mac though so there's no way to ensure mac support doesn't break through CI. Also, I don't have a mac so I can't implement this and be sure that it actually works. However, I'm happy to accept patches that add mac support to Cross as long as we document that mac is considered a tier 2 platform that can unintentionally break on new releases.

**Comment by killercup** [comment]
@griff do you want to implement that? I just had a "it can't be that hard, right?" moment and looked at the code.

The first step is probably to adjust the `Host::is_supported` method to also check `needs_docker()`.

Then, it's a matter of supplying the docker call with the right toolchain. By default, it seems to just use what `rustc --print sysroot` says, which is the host's toolchain. Changing this to `stable-x86_64-unknown-linux-gnu` (for the Ubuntu images; make sure this is installed) would be my first try. Sadly that still doesn't seem to supply the right files for the actual target, and I have not idea where those live. `</lunchbreak>`

**Comment by japaric** [comment]
You probably need to install a Linux Rust toolchain on your mac. Something like `rustup toolchain add nightly-x86_64-unknown-linux-gnu`. Which is a little weird because you *can't* use that toolchain from the command line since it's a Linux / ELF binary. Then instead of `rustc --print sysroot` you would have to use something like `$(rustc --print sysroot)/../nightly-x86_64-unknown-linux-gnu`.

We could make Cross install the Linux toolchain but then Cross would the one picking the Rust channel / version the code will be compiled with.

**Comment by killercup** [comment]
@japaric yeah, I did that for the second step, but then it doesn't find the _target_ toolchains in the Docker image. (Which is where I stopped debugging it.)

> We could make Cross install the Linux toolchain but then Cross would the one picking the Rust channel / version the code will be compiled with.

True, but parsing the current toolchain and installing it with rustup is probably not that hard (think `(stable|beta|nightly)(-[\d-]+)?-(.+)`, only breaks for custom linked toolchains AFAICT). Actually, does Rustup have a `--message-format=json` flag or something like that? Would be quite helpful!

**Comment by japaric** [comment]
> but then it doesn't find the target toolchains in the Docker image.

Ohh, OK. That makes sense. When you do `rustup target` on the host you get mac binaries and those won't work on the Linux VM. I think there is some syntax for installing targets for a non-host toolchain using `rustup component` ... hmm maybe something like `$HOST-rust-std-$TARGET`. Better check what rustup does on Windows; since there are two toolchains there (GNU and MSVC) it has deal with this somehow.

**Comment by xoac** [comment]
> Sounds good to me! Travis CI doesn't support docker for mac though so there's no way to ensure mac support doesn't break through CI

I am working on [rust-azure-pipelines](https://github.com/xoac/rust-azure-pipelines) maybe changing from travis to azure pipelines would be a good move? It will alow you test cross on Windows Linux and macOS agents

**Comment by xoac** [comment]
#131
