### ISSUE TITLE
std::env::home_dir() cannot write to home directory when using cross

### ISSUE THREAD

**Issue by chrlie** [rust-embedded/cross#121]
My crate uses [`std::env::home_dir()`](https://doc.rust-lang.org/std/env/fn.home_dir.html) to create a subdirectory in the user's home directory. The problem is that this directory is uncreatable using `cross` on Travis.

I don't know much about Docker, but I suspect that this is related to it. How is this environment variable treated within a Docker container? What's the cleanest way to get `$HOME` working within the crate running with `cross`?

**Comment by japaric** [comment]
Cross doesn't allow modification of any directory outside of the Cargo project (cf. [caveats](https://github.com/japaric/cross#caveats--gotchas)). If you need to modify $HOME for some test I would suggest [setting] that variable to some [temporary directory] within the unit test / test runner.

[setting]: https://doc.rust-lang.org/std/env/fn.set_var.html
[temporary directory]: https://crates.io/crates/tempdir

> What's the cleanest way to get $HOME working within the crate running with cross?

You can ["passthrough"] the HOME variable so that it will have the right value within the Docker container but as I said binaries executed within the container won't be able to modify any directory outside of the Cargo project.

["passthrough"]: https://github.com/japaric/cross#passing-environment-variables-into-the-build-environemnt

**Comment by jamesmunns** [comment]
Hey @chrlie, is this still an issue for you? As far as I can tell this is "as designed" behaviour.

**Comment by chrlie** [comment]
This is still an issue but I understand that it's also very much an edge case. "As designed" works for me and you can close this.
