### ISSUE TITLE
Please update FreeBSD version

### ISSUE THREAD

**Issue by kinnison** [rust-embedded/cross#274]
The FreeBSD version in the `cross` dockers is `10.2` which is (a) very old/unsupported and (b) too old to allow building of `rustup`.  Could you update this to at least `10.3` please?

**Comment by reitermarkus** [comment]
The FreeBSD images are now completely disabled because they are not building anymore. If you need them, please consider sending a PR to fix them.

**Comment by asomers** [comment]
FYI, a better option for FreeBSD is to run natively with www.cirrus-ci.com .

**Comment by ssokolow** [comment]
@asomers That assumes the person is trying to build an open-source project rather than, for example, trying to cross-compile something that isn't open-source for deployment to [NearlyFreeSpeech.NET](https://www.nearlyfreespeech.net/) without paying for the *a la carte* compute units to run the compile on their end.
