### ISSUE TITLE
error: no such subcommand: `wasm`

### ISSUE THREAD

**Issue by AndonMitev** [rust-embedded/cross#572]
Hello I'm running on Windows 10. I have been successfully installed cargo wasm

![image](https://user-images.githubusercontent.com/32274987/125745903-6fddab80-75ec-4fc0-883e-cf27e2ce11e1.png)

But when I execute:

`cargo wasm` => `error: no such subcommand: `wasm`

Any ideas how to fix it?

**Comment by Emilgardis** [comment]
Hi @AndonMitev 

This is the repository for the rust cross tool for cross compiling executables. Did you mean to post this issue here?

For cross, it would not be able to run `cargo wasm` as it only enables cross functionality on certain subcommands.

as for your issue, I think this is due to the executable not being installed properly. 

`error: no such subcommand` comes from cargo.

[Custom cargo subcommands](https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands) require a executable named `cargo-*` present in path. You do not have an executable named `cargo-wasm` in this directory you've shown. I presume its not anywhere else in your $env:PATH either.

if you meant to install [cargo-wasm](https://github.com/mgattozzi/cargo-wasm), try installing `cargo-wasm` again with `cargo install --force cargo-wasm`

I'm closing this issue as answered.

Either you've hit a limitation with cross, i.e it doesn't work for all subcommands, or you've hit an issue with your installation of the executable.
